import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarLayout from "@/components/sidebar-layout";
import IconBar from "@/components/icon-bar";
import { Toaster } from "sonner";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const chillaxFont = localFont({
  src: [
    {
      path: "../public/fonts/Chillax-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/Chillax-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Chillax-Semibold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/Chillax-Bold.woff2",
      weight: "700",
    },
  ],
  variable: "--font-chillax",
});

export const pallyFont = localFont({
  src: [
    {
      path: "../public/fonts/Pally-Bold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/Pally-Medium.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/Pally-Regular.woff2",
      weight: "400",
    },
  ],
  variable: "--font-pally",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TerpMe",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${pallyFont.variable} ${chillaxFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased transition-colors duration-300`}
      >
        <ThemeProvider
          attribute="class"
          enableSystem={false}
          defaultTheme="light"
        >
          <Toaster
            position="top-center"
            style={{ transform: "translateX(-10%)" }}
            richColors
          />
          <IconBar></IconBar>
          <SidebarLayout>{children}</SidebarLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
